---
# tasks file for ansible-role-win-vmwareoptimization
- name: Download PSTools
  ansible.windows.win_get_url:
    url: '{{ ps_tools_download_url }}'
    dest: '{{ vmware_optimization_tool_install_path }}\{{ ps_tools_filename_zip }}'
    force: no

- name: PSTools - Unzip
  community.windows.win_unzip:
    src: '{{ vmware_optimization_tool_install_path }}\{{ ps_tools_filename_zip }}'
    dest: '{{ vmware_optimization_tool_install_path }}\'
    delete_archive: yes

- name: Download VMwareHorizonOSOptimizationTool
  ansible.windows.win_get_url:
    url: '{{ vmware_optimization_tool_download_url }}'
    dest: '{{ vmware_optimization_tool_install_path }}\{{ vmware_optimization_tool_filename_exe }}'
    force: no

- name: Exec VMwareHorizonOSOptimizationTool
  ansible.windows.win_command: 'psexec.exe -accepteula -nobanner {{ ps_tools_commandline_args | default(omit) }} {{ vmware_optimization_tool_install_path }}\{{ vmware_optimization_tool_filename_exe }} {{ vmware_optimization_tool_commandline_args }}'
  args:
    chdir: '{{ vmware_optimization_tool_install_path }}'
  register: output